Added pubsub imports and Removed stdout, stderr redirection
Wrye Mash Log would always be empty and therefore useless to determine error

Added pubsub back because the error produced by mash.exe was:

AttributeError: 'module' object has no attribute 'Publisher'